---
hostname: N9K1

features:
- feature: vpc
- feature: hsrp
- feature: interface-vlan
- feature: ospf
- feature: lacp

lo_interfaces:
  - interface: lo0
    address: 10.1.1.6
    mask: 255.255.255.255

vlans:
  - vlan: 10
    name: Server-1_Data
  - vlan: 20
    name: Server-2_Data

vpc_domain:
  - domain: 100
    role_priority: 8192
    keepalive_dst: 172.16.1.17
    keepalive_src: 172.16.1.16

vpc_peer_link:
  - interface: Port-channel1

access_ports:
  - access_port: Port-channel2
    description: To Server-1
    vlan: 10
  - access_port: Port-channel3
    description: To Server-2
    vlan: 20

l2_pc_members:
  - description: To N9K2 Eth1/1
    interface: Ethernet1/1
    group: 1
  - description: To N9K2 Eth1/2
    interface: Ethernet1/2
    group: 1
  - description: To Server-1 Eth1
    interface: Ethernet1/5
    group: 2
  - description: To Server-2 Eth1
    interface: Ethernet1/6
    group: 3

l2_pc_interfaces:
  - interface: Port-channel1
  - interface: Port-channel2
  - interface: Port-channel3

vpcs:
  - interface: Port-channel2
    vpc: 2
  - interface: Port-channel3
    vpc: 3

trunks:
  - trunk: Port-channel1
    allowed_vlans: 10,20

l3_interfaces:
  - interface: Ethernet1/3
    description: N9K1-SW1 Transit
    address: 10.10.12.14
    mask: 255.255.255.252
  - interface: Ethernet1/4
    description: N9K1-SW2 Transit
    address: 10.10.12.30
    mask: 255.255.255.252

ospf:
  - interface: Loopback0
    area: 0
  - interface: Ethernet1/3
    area: 0
  - interface: Ethernet1/4
    area: 0

ospf_interfaces:
  - interface: Ethernet1/3
  - interface: Ethernet1/4