---
- connection: local
  gather_facts: False
  hosts: apics
  vars_files:
  - group_vars/aci.yml
  
  tasks:
  
    - name: Add tenants
      aci_tenant:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        private_key: "{{ private_key }}"
        validate_certs: "{{ validate_certs }}"
        tenant: "{{ item.name }}"
        description: "{{ item.description }}"
        state: present
      delegate_to: localhost
      with_items: "{{ tenants }}"