---
- connection: network_cli
  gather_facts: False
  hosts: ios_nodes
  vars_files:
  - group_vars/ios.yml

  tasks:

  - name: Backup (ios)
    ios_config:
      backup: yes
    register: backup_ios_location

- connection: network_cli
  gather_facts: False
  hosts: nxos_9ks
  vars_files:
  - group_vars/nxos.yml

  tasks:

  - name: Backup (nxos)
    nxos_config:
      backup: yes
    register: backup_nxos_location