---
- name: Configure IOS trunks
  connection: network_cli
  gather_facts: False
  hosts: ios_switches
  vars_files:
  - group_vars/ios.yml

  tasks:

  - name: Configure trunks
    ios_config:
      lines:
        - switchport
        - switchport trunk encapsulation dot1q
        - switchport mode trunk
        - switchport trunk allowed vlan {{ item.allowed_vlans }}
      parents: interface {{ item.trunk }}
    with_items: "{{ trunks }}"

- name: Configure NXOS trunks
  connection: network_cli
  gather_facts: False
  hosts: nxos_9ks
  vars_files:
  - group_vars/nxos.yml

  tasks:
  
  - name: Configure trunks
    nxos_config:
      lines:
        - switchport
        - switchport mode trunk
        - spanning-tree port type network
        - switchport trunk allowed vlan {{ item.allowed_vlans }}
      parents: interface {{ item.trunk }}
    with_items: "{{ trunks }}"