---
- name: Configure IOS VLANs
  connection: network_cli
  gather_facts: False
  hosts: ios_switches
  vars_files:
  - group_vars/ios.yml

  tasks:

  - name: Configure VLANs
    ios_config:
      lines:
        - name {{ item.name }}
      parents: vlan {{ item.vlan }}
    with_items: "{{ vlans }}"

- name: Configure NXOS VLANs
  connection: network_cli
  gather_facts: False
  hosts: nxos_9ks
  vars_files:
  - group_vars/nxos.yml

  tasks:

  - name: Configure VLANs
    nxos_config:
      lines:
        - name {{ item.name }}
      parents: vlan {{ item.vlan }}
    with_items: "{{ vlans }}"
