---
- connection: network_cli
  gather_facts: False
  hosts: switches
  vars_files:
  - group_vars/ios.yml

  tasks:

  - name: Configure VLANs (ios)
    ios_config:
      lines:
        - name {{ item.name }}
      parents: vlan {{ item.vlan }}
    with_items: "{{ vlans }}"

- connection: network_cli
  gather_facts: False
  hosts: 9ks
  vars_files:
  - group_vars/nxos.yml

  tasks:

  - name: Configure VLANs (nxos)
    nxos_config:
      lines:
        - name {{ item.name }}
      parents: vlan {{ item.vlan }}
    with_items: "{{ vlans }}"
