---
- import_playbook: config_hostname.yml
- import_playbook: config_banner.yml
- import_playbook: config_loopbacks.yml
- import_playbook: config_vlans.yml
- import_playbook: config_l2port-channels.yml
- import_playbook: config_vpc_global.yml
- import_playbook: config_vpcs.yml
- import_playbook: config_access_ports.yml
- import_playbook: config_trunks.yml
- import_playbook: config_l3int.yml
- import_playbook: enable_interfaces.yml
- import_playbook: config_ospf.yml
- import_playbook: config_bgp.yml
