---
- connection: network_cli
  gather_facts: False
  hosts: switches
  vars_files:
  - group_vars/ios.yml

  tasks:

  - name: Configure layer 2 port-channel members
    ios_config:
      lines:
        - switchport
        - description {{ item.description }}
        - no shutdown
        - channel-group {{ item.group }} mode active
      parents: interface {{ item.interface }}
    with_items: "{{ l2_pc_members }}"

#  - name: Configure layer 2 port-channel interfaces
#    ios_config:
#      lines:
#        - switchport
#      parents: interface {{ item.interface }}
#    with_items: "{{ l2_pc_interfaces }}"

- connection: network_cli
  gather_facts: False
  hosts: 9ks
  vars_files:
  - group_vars/nxos.yml

  tasks:
  
  - name: Check NXOS LACP feature
    nxos_config:
      lines:
      - feature lacp

  - name: Configure NXOS layer 2 port-channel members
    nxos_config:
      lines:
        - switchport
        - description {{ item.description }}
        - channel-group {{ item.group }} mode active
        - no shutdown
      parents: interface {{ item.interface }}
    with_items: "{{ l2_pc_members }}"

#  - name: Configure NXOS layer 2 port-channel interfaces
#    nxos_config:
#      lines:
#        - switchport
#        - no shutdown
#      parents: interface {{ item.interface }}
#    with_items: "{{ l2_pc_interfaces }}"
