---
- name: Configure banners
  connection: network_cli
  gather_facts: False
  hosts: ios_nodes
  vars_files:
  - group_vars/ios.yml

  tasks:
  
  - name: Login banners
    ios_banner:
      banner: login
      text: "{{ lookup('file', './config_partial/raw_banner.cfg') }}"
      state: present
      
  - name: Exec banners
    ios_banner:
      banner: exec
      text: "{{ lookup('file', './config_partial/raw_banner.cfg') }}"
      state: present