---
- name: Configure IOS loopbacks
  connection: network_cli
  gather_facts: False
  hosts: ios_nodes
  vars_files:
  - group_vars/ios.yml

  tasks:

  - name: Configure loopback interfaces
    ios_config:
      lines:
        - ip address {{ item.address }} {{ item.mask }}
      parents: interface {{ item.interface }}
    with_items: "{{ lo_interfaces }}"

- name: Configure NXOS loopbacks
  connection: network_cli
  gather_facts: False
  hosts: nxos_9ks
  vars_files:
  - group_vars/nxos.yml

  tasks:

  - name: Configure loopback interfaces (nxos)
    nxos_config:
      lines:
        - ip address {{ item.address }} {{ item.mask }}
      parents: interface {{ item.interface }}
    with_items: "{{ lo_interfaces }}"
