---
- name: Configure BGP
  connection: network_cli
  gather_facts: False
  hosts: bgp_ios
  vars_files:
  - group_vars/ios.yml

  tasks:
    
  - name: BGP (global)
    ios_config:
      lines:
        - bgp router-id {{ item.rid }}
        - no bgp default ipv4-unicast
      parents: router bgp {{ item.as }}
    with_items: "{{ bgp_global }}"

  - name: Redistribute OSPF to BGP (global)
    ios_config:
      lines:
        - redistribute ospf 100 route-map OSPF_BGP
      parents: router bgp {{ item.as }}
    with_items: "{{ bgp_global }}"
    when: ospf_bgp is defined

  - name: OSPF to BGP route-map
    ios_config:
      lines:
        - route-map OSPF_BGP permit 10
    when: ospf_bgp is defined

  - name: iBGP neighbors (global)
    ios_config:
      lines:
        - neighbor {{ item.neighbor }} remote-as {{ item.remote_as }}
        - neighbor {{ item.neighbor }} update-source {{ item.update_source }}
      parents: router bgp {{ bgp_global[0].as }}
    with_items: "{{ ibgp_neighbors }}"
    when: ibgp_neighbors is defined
    
  - name: iBGP neighbors (AF)
    ios_config:
      lines:
        - neighbor {{ item.neighbor }} activate
        - neighbor {{ item.neighbor }} next-hop-self
        - neighbor {{ item.neighbor }} send-community both
      parents:
        - router bgp {{ bgp_global[0].as }}
        - address-family ipv4 unicast
    with_items: "{{ ibgp_neighbors }}"
    when: ibgp_neighbors is defined

  - name: eBGP neighbors (global)
    ios_config:
      lines:
        - neighbor {{ item.neighbor }} remote-as {{ item.remote_as }}
        - neighbor {{ item.neighbor }} update-source {{ item.update_source }}
      parents: router bgp {{ bgp_global[0].as }}
    with_items: "{{ ebgp_neighbors }}"
    
  - name: eBGP neighbors (AF)
    ios_config:
      lines:
        - neighbor {{ item.neighbor }} activate
        - neighbor {{ item.neighbor }} send-community both
      parents:
        - router bgp {{ bgp_global[0].as }}
        - address-family ipv4 unicast
    with_items: "{{ ebgp_neighbors }}"

  - name: eBGP originate default (AF)
    ios_config:
      lines:
        - neighbor {{ item.neighbor }} default-originate
      parents:
        - router bgp {{ bgp_global[0].as }}
        - address-family ipv4 unicast
    when: item.originate_default is defined
    with_items: "{{ ebgp_neighbors }}"

  - name: eBGP maximum paths (AF)
    ios_config:
      lines:
        - maximum-paths {{ ebgp_max_paths }}
      parents:
        - router bgp {{ bgp_global[0].as }}
        - address-family ipv4 unicast
    when: ebgp_max_paths is defined

  - name: Advertise networks
    ios_config:
      lines:
        - network {{ item.network }} mask {{ item.mask }}
      parents: router bgp {{ bgp_global[0].as }}
    with_items: "{{ bgp_networks }}"
    when: bgp_networks is defined