---
- connection: network_cli
  gather_facts: False
  hosts: switches
  vars_files:
  - group_vars/ios.yml

  tasks:

  - name: Configure layer 2 port-channel members
    ios_config:
      lines:
        - switchport
        - description {{ item.description }}
        - channel-group {{ item.group }} mode active
      parents: interface {{ item.interface }}
    with_items: "{{ l2_pc_members }}"

- connection: network_cli
  gather_facts: False
  hosts: 9ks
  vars_files:
  - group_vars/nxos.yml

  tasks:
  
  - name: Check NXOS LACP feature
    nxos_feature:
      feature: lacp
      state: enabled

  - name: Configure NXOS layer 2 port-channel members
    nxos_config:
      lines:
        - switchport
        - description {{ item.description }}
        - channel-group {{ item.group }} mode active
      parents: interface {{ item.interface }}
    with_items: "{{ l2_pc_members }}"
