---
- name: Configure IOS layer 2 port-channels
  connection: network_cli
  gather_facts: False
  hosts: ios_switches
  vars_files:
  - group_vars/ios.yml

  tasks:

  - name: Port-channel members
    ios_config:
      lines:
        - switchport
        - description {{ item.description }}
        - channel-group {{ item.group }} mode active
      parents: interface {{ item.interface }}
    with_items: "{{ l2_pc_members }}"

- name: Configure NXOS layer 2 port-channels
  connection: network_cli
  gather_facts: False
  hosts: nxos_9ks
  vars_files:
  - group_vars/nxos.yml

  tasks:
  
  - name: Check LACP feature
    nxos_feature:
      feature: lacp
      state: enabled

  - name: Port-channel members
    nxos_config:
      lines:
        - switchport
        - description {{ item.description }}
        - channel-group {{ item.group }} mode active
      parents: interface {{ item.interface }}
    with_items: "{{ l2_pc_members }}"
