---
- name: Configure IOS access ports
  connection: network_cli
  gather_facts: False
  hosts: ios_switches
  vars_files:
  - group_vars/ios.yml

  tasks:

  - name: Access ports
    ios_config:
      lines:
        - description {{ item.description }}
        - switchport
        - switchport mode access
        - switchport access vlan {{ item.vlan }}
        - spanning-tree portfast
      parents: interface {{ item.access_port }}
    with_items: "{{ access_ports }}"

- connection: network_cli
  name: Configure NXOS access ports
  gather_facts: False
  hosts: nxos_9ks
  vars_files:
  - group_vars/nxos.yml

  tasks:

  - name: Access ports
    nxos_config:
      lines:
        - description {{ item.description }}
        - switchport
        - switchport mode access
        - switchport access vlan {{ item.vlan }}
        - spanning-tree port type edge
      parents: interface {{ item.access_port }}
    with_items: "{{ access_ports }}"
