---
- name: Configure layer 3 interfaces
  connection: network_cli
  gather_facts: False
  hosts: nodes
  vars_files:
  - group_vars/ios.yml

  tasks:

  - name: L3 interfaces (ios)
    ios_config:
      lines:
        - description {{ item.description }}
        - ip address {{ item.address }} {{ item.mask }}
        - no ip redirects
        - no ip proxy-arp
      parents: interface {{ item.interface }}
    with_items: "{{ l3_interfaces }}"

- connection: network_cli
  gather_facts: False
  hosts: 9ks
  vars_files:
  - group_vars/nxos.yml

  tasks:

  - name: L3 interfaces (nxos)
    nxos_config:
      lines:
        - description {{ item.description }}
        - no switchport
        - ip address {{ item.address }} {{ item.mask }}
        - no ip redirects
        - no ip proxy-arp
      parents: interface {{ item.interface }}
    with_items: "{{ l3_interfaces }}"

  - name: Check NXOS interface-vlan feature
    nxos_feature:
      feature: interface-vlan
      state: enabled

  - name: Check NXOS hsrp feature
    nxos_feature:
      feature: hsrp
      state: enabled

  - name: SVIs (nxos)
    nxos_config:
      lines:
        - description {{ item.description }}
        - ip address {{ item.address }} {{ item.mask }}
        - no ip redirects
        - no ip proxy-arp
      parents: interface {{ item.interface }}
    with_items: "{{ svis }}"

  - name: HSRP (nxos)
    nxos_config:
      lines:
        - priority {{ item.hsrp_priority }}
        - ip {{ item.hsrp_ip }}
      parents:
        - interface {{ item.interface }}
        - hsrp {{ item.hsrp_group }}
    with_items: "{{ svis }}"