---
- name: Configure IOS hostnames
  connection: network_cli
  gather_facts: False
  hosts: ios_nodes
  vars_files:
  - group_vars/ios.yml

  tasks:
    
  - name: Hostnames
    ios_config:
      lines:
        - hostname {{ inventory_hostname }}

- name: Configure NXOS hostnames
  connection: network_cli
  gather_facts: False
  hosts: nxos_9ks
  vars_files:
  - group_vars/nxos.yml

  tasks:
  
  - name: Hostnames
    nxos_config:
      lines:
        - hostname {{ inventory_hostname }}