---
l3_interfaces:
  - interface: Vlan101
    description: R1 Transit
    address: 10.10.12.1
    mask: 255.255.255.252
  - interface: Vlan102
    description: R2 Transit
    address: 10.10.12.5
    mask: 255.255.255.252
  - interface: Vlan103
    description: SW1-SW2 Transit
    address: 10.10.12.9
    mask: 255.255.255.252
  - interface: Vlan104
    description: SW1-N9K1 Transit
    address: 10.10.12.13
    mask: 255.255.255.252
  - interface: Vlan105
    description: SW1-N9K2 Transit
    address: 10.10.12.17
    mask: 255.255.255.252