---
hostname: SW1

lo_interfaces:
  - interface: loopback0
    address: 10.1.1.3
    mask: 255.255.255.255

vlans:
  - vlan: 101
    name: R1_Transit
  - vlan: 102
    name: R2_Transit
  - vlan: 103
    name: SW1-SW2_Transit
  - vlan: 104
    name: SW1-N9K1_Transit
  - vlan: 105
    name: SW1-N9K2_Transit

l2_pc_members:
  - description: To SW2 Gi0/3
    interface: GigabitEthernet0/3
    group: 1
  - description: To SW2 Gi1/0
    interface: GigabitEthernet1/0
    group: 1

l2_pc_interfaces:
  - description: To SW2 Po1
    interface: Port-channel1

trunks:
  - trunk: Port-channel1
    allowed_vlans: 103

access_ports:
  - access_port: GigabitEthernet0/1
    description: To R2 Gi0/2
    vlan: 102
  - access_port: GigabitEthernet0/2
    description: To R1 Gi0/1
    vlan: 101
  - access_port: GigabitEthernet1/1
    description: To N9K1 Eth1/3
    vlan: 104
  - access_port: GigabitEthernet1/2
    description: To N9K2 Eth1/3
    vlan: 105

l3_interfaces:
  - interface: Vlan101
    description: R1 Transit
    address: 10.10.12.1
    mask: 255.255.255.252
  - interface: Vlan102
    description: R2 Transit
    address: 10.10.12.5
    mask: 255.255.255.252
  - interface: Vlan103
    description: SW1-SW2 Transit
    address: 10.10.12.9
    mask: 255.255.255.252
  - interface: Vlan104
    description: SW1-N9K1 Transit
    address: 10.10.12.13
    mask: 255.255.255.252
  - interface: Vlan105
    description: SW1-N9K2 Transit
    address: 10.10.12.17
    mask: 255.255.255.252

ospf:
  - network: 10.10.12.0
    wildcard: 0.0.0.3
    area: 0
  - network: 10.10.12.4
    wildcard: 0.0.0.3
    area: 0
  - network: 10.1.1.3
    wildcard: 0.0.0.0
    area: 0
  - network: 10.10.12.8
    wildcard: 0.0.0.3
    area: 0
  - network: 10.10.12.12
    wildcard: 0.0.0.3
    area: 0
  - network: 10.10.12.16
    wildcard: 0.0.0.3
    area: 0

ospf_interfaces:
  - interface: Vlan101
  - interface: Vlan102
  - interface: Vlan103
  - interface: Vlan104
  - interface: Vlan105