---
l2_pc_members:
  - description: To SW1 Gi0/3
    interface: GigabitEthernet0/3
    group: 1
  - description: To SW1 Gi1/0
    interface: GigabitEthernet1/0
    group: 1

l2_pc_interfaces:
  - description: To SW1 Po1
    interface: Port-channel1