---
hostname: R2

lo_interfaces:
  - interface: lo0
    address: 10.1.1.2
    mask: 255.255.255.255

l3_interfaces:
  - interface: Gi0/1
    description: SW2 Transit
    address: 10.10.12.26
    mask: 255.255.255.252
  - interface: Gi0/2
    description: SW1 Transit
    address: 10.10.12.6
    mask: 255.255.255.252
  - interface: Gi0/3
    description: R3 Transit
    address: 10.10.12.41
    mask: 255.255.255.252

ospf:
  - network: 10.10.12.24
    wildcard: 0.0.0.3
    area: 0
  - network: 10.1.1.2
    wildcard: 0.0.0.0
    area: 0
  - network: 10.10.12.4
    wildcard: 0.0.0.3
    area: 0

ospf_interfaces:
  - interface: Gi0/1
  - interface: Gi0/2

ospf_oirigate_default: True

bgp_global:
  - as: 65000
    rid: "{{ lo_interfaces[0].address }}"

ibgp_neighbors:
  - neighbor: 10.1.1.1
    update_source: "{{ lo_interfaces[0].interface }}"
    remote_as: 65000

ebgp_neighbors:
  - neighbor: 10.10.12.42
    update_source: "{{ l3_interfaces[2].interface }}"
    remote_as: 12345

ospf_bgp: True