---
l3_interfaces:
  - interface: Gi0/1
    description: SW2 Transit
    address: 10.10.12.2
    mask: 255.255.255.252
  - interface: Gi0/2
    description: SW2 Transit
    address: 10.10.12.22
    mask: 255.255.255.252
  - interface: Gi0/3
    description: R3 Transit
    address: 10.10.12.37
    mask: 255.255.255.252