---
lo_interfaces:
  - interface: lo0
    address: 10.1.1.1
    mask: 255.255.255.255

l3_interfaces:
  - interface: Gi0/1
    description: SW2 Transit
    address: 10.10.12.2
    mask: 255.255.255.252
  - interface: Gi0/2
    description: SW2 Transit
    address: 10.10.12.22
    mask: 255.255.255.252
  - interface: Gi0/3
    description: R3 Transit
    address: 10.10.12.37
    mask: 255.255.255.252

ospf:
  - network: 10.10.12.0
    wildcard: 0.0.0.3
    area: 0
  - network: 10.1.1.1
    wildcard: 0.0.0.0
    area: 0