---
hostname: R3

lo_interfaces:
  - interface: lo0
    address: 10.1.1.5
    mask: 255.255.255.255

l3_interfaces:
  - interface: Gi0/1
    description: R1 Transit
    address: 10.10.12.38
    mask: 255.255.255.252
  - interface: Gi0/2
    description: R2 Transit
    address: 10.10.12.42
    mask: 255.255.255.252

bgp_global:
  - as: 12345
    rid: "{{ lo_interfaces[0].address }}"

bgp_networks:
  - network: 10.10.12.36
    mask: 255.255.255.252
  - network: 10.10.12.40
    mask: 255.255.255.252
  - network: "{{ lo_interfaces[0].address }}"
    mask: "{{ lo_interfaces[0].mask }}"

ebgp_neighbors:
  - neighbor: 10.10.12.37
    update_source: "{{ l3_interfaces[0].interface }}"
    remote_as: 65000
    originate_default: True
  - neighbor: 10.10.12.41
    update_source: "{{ l3_interfaces[1].interface }}"
    remote_as: 65000
    originate_default: True

ebgp_max_paths: 2