---
hostname: R3

lo_interfaces:
  - interface: lo0
    address: 10.1.1.5
    mask: 255.255.255.255

l3_interfaces:
  - interface: Gi0/1
    description: R1 Transit
    address: 10.10.12.38
    mask: 255.255.255.252
  - interface: Gi0/2
    description: R2 Transit
    address: 10.10.12.42
    mask: 255.255.255.252

bgp_global:
  - as: 12345
    rid: "{{ lo_interfaces[0].address }}"

ibgp_neighbors:
  - neighbor:
    update_source:
    remote_as:

ebgp_neighbors:
  - neighbor: 10.10.12.37
    update_source: "{{ l3_interfaces[0].interface }}"
    remote_as: 65000
  - neighbor: 10.10.12.41
    update_source: "{{ l3_interfaces[1].interface }}"
    remote_as: 12345